camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
model_path: light_classification/model/model_8_keep_aspect_ratio.hd5
model_width: 86
model_height: 64